apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ahmadsawaed99/backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: MongoDb__PathToCAFile
              value: /app/certs/global-bundle.pem
          volumeMounts:
            - name: docdb-ca
              mountPath: /app/certs
              readOnly: true
      volumes:
        - name: docdb-ca
          configMap:
            name: docdb-ca
            items:
              - key: global-bundle.pem
                path: global-bundle.pem
---
apiVersion: v1
kind: Service
metadata:
  name: backend-lb-srv
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080